languageCode = 'en-us'
baseURL = 'https://rosettea.github.io/Hilbish'
title = 'Hilbish'
theme = 'hsh'
enableGitInfo = true

[menu]
[[menu.nav]]
	identifier = 'home'
	name = 'Home'
	pageref = '/'
	weight = 1
[[menu.nav]]
	identifier = 'install'
	name = 'Install'
	pageref = '/install'
	weight = 2
[[menu.nav]]
	identifier = 'docs'
	name = 'Docs'
	pageref = '/docs'
	weight = 3
[[menu.nav]]
	identifier = 'blog'
	name = 'Blog'
	pageref = '/blog'
	weight = 4

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
lineNos = true
lineNumbersInTable = false
noClasses = false
codeFences = true
guessSyntax = true
tabWidth = 4

[author]
	[author.sammyette]
		name = 'sammyette'
		picture = 'https://avatars1.githubusercontent.com/u/38820196?s=460&u=b9f4efb2375bae6cb30656d790c6e0a2939327c0&v=4'
