name: Build

on:
  - push
  - pull_request

jobs:
  build:
    name: ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - build: linux-amd64
            os: ubuntu-latest
          - build: darwin-amd64
            os: macOS-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Build
        run: make hilbiline

