name: Generate docs

on:
  push:
    branches: [master]

jobs:
  gen:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run docgen
        run: go run cmd/docgen/docgen.go
      - name: Run Lua docgen
        run: ./hilbish cmd/docgen/docgen.lua
      - name: Commit new docs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: [ci] generate new docs"
          file_pattern: docs/ emmyLuaDocs/
