name: Generate docs

on:
  push:
    branches:
      - master
      - docs-refactor

jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Download Task
        run: 'sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d'
      - name: Build
        run: ./bin/task
      - name: Run docgen
        run: go run cmd/docgen/docgen.go
      - name: Run lua docgen
        run: ./hilbish cmd/docgen/docgen.lua
      - name: Commit new docs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: [ci] generate new docs"
          file_pattern: docs/ emmyLuaDocs/
